import type { Metadata } from "next";
import {Bitter } from "next/font/google";
import "./globals.css";

const bitter = Bitter({
  subsets: ["latin"],
  weight: ["400","700"],
  display: "swap",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={bitter.className}>
      <body>
        <header/>
        {children}
      </body>
    </html>
  );
}
